/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserStatus = "active" | "disabled" | "invited";

export interface Account {
  /**
   * The access token of the account. Returned by the provider
   */
  accessToken: string | null;
  /**
   * The time when the access token expires
   */
  accessTokenExpiresAt: Timestamp | null;
  /**
   * The id of the account as provided by the SSO or equal to user_id for credential accounts
   */
  accountId: string;
  /**
   * The time when the account was created
   */
  createdAt: Generated<Timestamp>;
  /**
   * Unique identifier for each account
   */
  id: Generated<string>;
  /**
   * The id token returned from the provider
   */
  idToken: string | null;
  /**
   * The password of the account. Mainly used for email and password authentication
   */
  password: string | null;
  /**
   * The id of the provider
   */
  providerId: string;
  /**
   * The refresh token of the account. Returned by the provider
   */
  refreshToken: string | null;
  /**
   * The time when the refresh token expires
   */
  refreshTokenExpiresAt: Timestamp | null;
  /**
   * The scope of the account. Returned by the provider
   */
  scope: string | null;
  /**
   * The time when the account was last updated
   */
  updatedAt: Generated<Timestamp>;
  /**
   * The id of the user
   */
  userId: string;
}

export interface Credential {
  createdAt: Generated<Timestamp | null>;
  email: string | null;
  id: Generated<string>;
  label: string | null;
  primary: boolean | null;
  provider: string;
  providerAccountId: string | null;
  tokens: Json;
  updatedAt: Generated<Timestamp | null>;
  userId: string;
}

export interface Session {
  /**
   * The time when the session was created
   */
  createdAt: Generated<Timestamp>;
  /**
   * The time when the session expires
   */
  expiresAt: Timestamp;
  /**
   * Unique identifier for each session
   */
  id: Generated<string>;
  /**
   * The IP address of the device
   */
  ipAddress: string | null;
  /**
   * The unique session token
   */
  token: string;
  /**
   * The time when the session was last updated
   */
  updatedAt: Generated<Timestamp>;
  /**
   * The user agent information of the device
   */
  userAgent: string | null;
  /**
   * The id of the user
   */
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp | null>;
  email: string | null;
  /**
   * Whether the user email is verified
   */
  emailVerified: Generated<boolean>;
  id: Generated<string>;
  /**
   * The image URL of the user
   */
  image: string | null;
  lastInteractionAt: Timestamp | null;
  name: string | null;
  status: Generated<UserStatus>;
  timeZone: string | null;
  /**
   * The time when the user was last updated
   */
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  /**
   * The time when the verification was created
   */
  createdAt: Generated<Timestamp>;
  /**
   * The time when the verification request expires
   */
  expiresAt: Timestamp;
  /**
   * Unique identifier for each verification
   */
  id: Generated<string>;
  /**
   * The identifier for the verification request
   */
  identifier: string;
  /**
   * The time when the verification was last updated
   */
  updatedAt: Generated<Timestamp>;
  /**
   * The value to be verified
   */
  value: string;
}

export interface DB {
  accounts: Account;
  credentials: Credential;
  sessions: Session;
  users: User;
  verifications: Verification;
}
