apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequencing-consultant-web
  labels:
    app: sequencing-consultant
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sequencing-consultant
      component: web
  template:
    metadata:
      labels:
        app: sequencing-consultant
        component: web
    spec:
      containers:
      - name: web
        image: image-registry.openshift-image-registry.svc:5000/dept-barc/sequencing-consultant-web:latest
        ports:
        - containerPort: 3001
          protocol: TCP
        env:
        - name: PORT
          value: "3001"
        - name: HOST
          value: "0.0.0.0"
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sequencing-consultant-secrets
              key: database-url
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: sequencing-consultant-secrets
              key: auth-secret
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: sequencing-consultant-secrets
              key: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: sequencing-consultant-secrets
              key: github-client-secret
        - name: PUBLIC_FORMSPREE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: sequencing-consultant-config
              key: formspree-endpoint
        - name: SITE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: sequencing-consultant-config
              key: site-base-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sequencing-consultant-web
  labels:
    app: sequencing-consultant
    component: web
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: sequencing-consultant
    component: web
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sequencing-consultant
  labels:
    app: sequencing-consultant
spec:
  to:
    kind: Service
    name: sequencing-consultant-web
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect 