# DO NOT COMMIT THIS FILE WITH ACTUAL SECRETS
# Copy this file to secrets.yaml and fill in your actual values
# Then create the secret with: oc create -f secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: sequencing-consultant-secrets
  labels:
    app: sequencing-consultant
type: Opaque
stringData:
  database-url: "postgresql://username:password@host:5432/database_name"
  auth-secret: "your-auth-secret-here"
  github-client-id: "your-github-client-id"
  github-client-secret: "your-github-client-secret" 